language: python
sudo: false
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip3 install mongo-connector"
  - "pip3 install mongo-orchestration"
services:
  - mongodb
  - elasticsearch
env:
  - PYTHONPATH=.
before_script:
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=3.6.1 bash
  - mongo-orchestration start
  - sleep 15
# command to run tests
script: python3 setup.py test