language: python
sudo: false
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip3 install mongo-connector"
  - "pip3 install mongo-orchestration"
services:
  - mongodb
env:
  - PYTHONPATH=.
before_script:
  - mongo-orchestration start
  - mongo test --eval 'rs.initiate();'
  - sleep 15
# command to run tests
script: python3 -m unittest discover